### ISSUE TITLE
Error when trying to dump 2D render as image but not as terminal image

### ISSUE THREAD

**Issue by pcs96** [jmd-dk/Nbody#2]
When run with the following content of the param-file:

```python3
# Non-parameter variable used to control the size of the simulation
_size = 128

# Input/output
initial_conditions = {
    'species': 'matter',
    'N'      : _size**3,
}
output_dirs = {
    'render2D' : paths['output_dir']
}
output_times = {
    'render2D' : logspace(log10(a_begin), log10(1), 100)
}
render2D_select = {
    'matter': {'data': False, 'image': True,  'terminal image': False},
}

# Numerical parameters
boxsize = 128*Mpc

# Cosmology
H0      = 67*km/(s*Mpc)
Ωcdm    = 0.27
Ωb      = 0.049
a_begin = 0.02

# Physics
select_forces = {
    'matter': {'gravity': ('pm', 2*_size)},
}

# Graphics
render2D_options = {
    'gridsize': {
        'matter': _size,
    },
    'terminal resolution': {
        'matter': 80,
    },
    'colormap': {
        'matter': 'inferno',
    },
}
```
concept produces the following error message instead of rendering the 2D image:

```
Traceback (most recent call last):
  File "graphics.pyx", line 568, in graphics.render2D
    BEGIN_UNICODE__DOUBLE__DASH__STRUCK__SPACE__CAPITAL__SPACE__R__END_UNICODE_237__DIV____LTH__double__GTH____OPAR__vmax_terminal__MIN__vmin_terminal__CPAR__ = <double>(237/<double>(vmax_terminal - vmin_terminal))
UnboundLocalError: local variable 'vmax_terminal' referenced before assignment
Exception ignored in: 'main.dump'
Traceback (most recent call last):
  File "graphics.pyx", line 568, in graphics.render2D
    BEGIN_UNICODE__DOUBLE__DASH__STRUCK__SPACE__CAPITAL__SPACE__R__END_UNICODE_237__DIV____LTH__double__GTH____OPAR__vmax_terminal__MIN__vmin_terminal__CPAR__ = <double>(237/<double>(vmax_terminal - vmin_terminal))
UnboundLocalError: local variable 'vmax_terminal' referenced before assignment
```

When run with ```'terminal image': True``` it completes successfully.

**Comment by jmd-dk** [comment]
Thanks for bringing this to my attention. It has now been fixed.

To update CO𝘕CEPT to the latest version which include the fix, do the following from the `concept` directory:

```bash
rm -rf ../.backup/ && ./concept -u update master && ./concept
```
